### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by MartianDays** [Dixon6/GMC-ALS#1]
![image](https://github.com/Dixon6/GMC-ALS/assets/15644824/08fa2835-1846-4741-a74a-ce83920385c3)

![image](https://github.com/Dixon6/GMC-ALS/assets/15644824/1aa82ca7-6a1b-4ff2-bf4b-02e8efe6302c)

With UE5.3.1 marketplace build, and GMC 2.0b1, project does not compile. Can not generate Visual Studio project files as the error demands, as the project itself is not a source build with C++ files. Unfortunately, have tried many times to build with no success. Have also attempted to open the project with UE 5.3.1 release source build, producing the same failed results.

**Comment by MartianDays** [comment]
Update: Removing Advanced Sessions and Advanced Sessions Steam plugins, both, allowed the project to compile - but seem to be required for the main menu level and game instance to function.

**Comment by Dixon6** [comment]
Main Menu level and game instance was just a quickly made steam implementation with advanced sessions to test online. You can probably just disregard them and create your own or use the GMC's built in GMCSteam. I personally was not knowledgeable enough in C++ to use GMCSteam.

**Comment by Ereliath** [comment]
The latest build fixes this issue.
Converting the project to a C++ project and generating a sln file was the solution.
