### ISSUE TITLE
Cannot Play Montages

### ISSUE THREAD

**Issue by ninjasdf** [Dixon6/GMC-ALS#6]
Not sure if this classifies as an issue but I wasn't sure where else to address this.

Normally, with ALS (specifically the C++ versions), when you want to play a full body montage animation, you set on the animation a curve for BasePose_N with a value of 1 for the duration of the animation.  Then on the Montage you make sure it is playing in the MovementActionGroup.BaseLayer.  This allows you to play the animation montage like you normally would, bypassing ALS' complex merging features.

However, doing this with your project still does not allow the animation to play.

How do I get a normal animation montage to play fully with this new system you've created?

P.S.  This combination of ALS and GMC is a great idea and your implementation has been awesome.  I've been following this project closely and am strongly considering using this instead of the other C++ implementation of ALS I've been using (https://github.com/dyanikoglu/ALS-Community).  Just trying to work through the above issue so I can begin testing this to see if it will fully meet my needs.

**Comment by Dixon6** [comment]
It might be due to the montage variable being set to none in one of the functions. (probably the roll one.) Grim is working on a montage update that will release sometime this week though. Once it's out I'll rework the montages and it will maybe fix the issue you're having.

**Comment by Dixon6** [comment]
Just pushed a new build with the montage changes! Let me know if you still have the issue. If not I'll close this as resolved!
